/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yatzoo;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
    }
}
