/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yatzoo;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void testPlayers() {
        String[] names = { "Simen", "Sebastian", "Morten" };
        Player[] players = Main.initPlayers(names);
        assertTrue(players[0].getName().equals(names[0]));
        assertTrue(players[1].getName().equals(names[1]));
        assertTrue(players[2].getName().equals(names[2]));

        assertTrue(players.length == names.length);
    }
}
