/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yatzoo;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test
    public void testPlayers() {
        String[] names = { "Simen", "Sebastian", "Morten" };
        Player[] players = Main.initPlayers(names);
        assertTrue(players[0].getClass().equals(names[0]));
        assertTrue(players[0].getClass().equals(names[1]));
        assertTrue(players[0].getClass().equals(names[2]));
    }
}
